cubicdaiya/nginx-build

- nginx-build.go
> Fix a help message.

- Gomfile
- module3rd.go
switched to the library under active development.
> ini: switched to go-ini.

- .gitignore
- Gomfile
- Makefile
- glide.lock
- glide.yaml
> vendoring: switched from gom to glide.

- message.go
- nginx-build.go
- option.go
The output of original flag.Usage() is too long.
> cutomized flag.Usage().

- README.md
- nginx-build.go
- option.go
- patch.go
- util/patch.go
> introduced new flags: `--patch` and `--patch-opt` for applying patch to nginx (v2)

- nginx-build.go
- util/patch.go
> patch: allowed multiflag for '--patch'.

- builder/const.go
> download pcre via HTTPS

- README.md
- builder/const.go
nginx-build can download all resources via HTTPS
> tengine is now available for HTTPS

- .github/workflows/go.yml
- .travis.yml
> ci: switch to GitHub Actions

- configure/configureopt.go
```
flag "with-perl_modules_path=" contains =
panic: flag "with-perl_modules_path=" contains =
```
> bugfix: made a typo in configure options.

- .github/workflows/go.yml
- nginx-build.go
refs https://github.com/cubicdaiya/nginx-build/issues/72
> cli: make -pcre unavailable.

- builder/builder.go
- builder/builder_test.go
- builder/const.go
- configure/configure_test.go
- nginx-build.go
fixes #72 
nginx is built with the PCRE2 by default from 1.21.5.
> revive -pcre option.

- Makefile
- message.go
- nginx-build.go
To automate release work. refs #78 #79
> cli: embed version by debug.ReadBuildInfo().

- .goreleaser.yml
GoReleaser did not work with current settings
> fix goreleaser.yml

- builder/const.go
> bumped default openssl version to 1.1.1q.

- .github/workflows/go.yml
- .github/workflows/release.yml
> ci: update go version to 1.19.x

- .github/workflows/go.yml
> ci: add -pcre in build testing.

- .github/workflows/go.yml
- README.md
- builder/builder.go
- builder/builder_test.go
- builder/const.go
- nginx-build.go
- option.go
- version.go
> add support for freenginx and remove support for tengine

- builder/const.go
Reverts cubicdaiya/nginx-build#149
> Revert "chore(deps): update dependency openresty/openresty to v1.25.3.2"

- .github/workflows/security.yml
This pull request introduces a new GitHub Actions workflow to enhance security by integrating vulnerability checks using `govulncheck`. The most important change is the addition of a new workflow configuration file.
Security enhancements:
* [`.github/workflows/security.yml`](diffhunk://#diff-6102d4f2cddb56c446459bde9bf8e8044b87ce3f98a24c2bba99debfd62461dcR1-R20): Added a new workflow named `govulncheck` that runs on pushes to the `master` branch, on pull requests, and on a daily schedule. This workflow uses the `golang/govulncheck-action` to check for vulnerabilities in the Go codebase.
> Add GitHub Actions workflow for govulncheck security scanning

- .github/workflows/go.yml
- config/modules.json.brotli
- module3rd/download.go
- module3rd/provide.go
This pull request introduces support for Brotli compression in the Nginx build process, enhances error handling and logging in the `module3rd` package, and refactors shell command execution for better reliability. Below are the most significant changes grouped by theme.
* Added a new workflow job `run-nginx-brotli` in `.github/workflows/go.yml` to build and run Nginx with Brotli compression.
* Introduced a new configuration file `config/modules.json.brotli` to include the Brotli module (`ngx_brotli`) with optimized build flags.
* Updated the `download` function in `module3rd/download.go` to improve error handling and logging when cloning Git repositories. Logs are now written to a file if verbose mode is disabled.
* Refactored the `provideShell` function in `module3rd/provide.go` to use …
> improve git clone to log output and simplify shell command execution

- CLAUDE.md
This pull request introduces a new documentation file, `CLAUDE.md`, to provide guidance on using the `nginx-build` tool and understanding its architecture. The document is aimed at developers and includes instructions for development commands, testing, architecture overview, key design patterns, and important configuration files.
* **Development Commands**: Lists commands for building, testing, formatting, and cleaning the `nginx-build` binary, along with examples for running tests on specific packages.
* **Architecture Overview**: Explains the organization of the codebase into key packages (`builder`, `configure`, `module3rd`, etc.) and their respective responsibilities, such as managing builds, third-party modules, and utility functions.
* **Key Design Patterns**: Highlights patterns …
> add CLAUDE.md

- .github/workflows/go.yml
- README.md
- builder/builder.go
- builder/builder_test.go
- builder/const.go
- download.go
- download_test.go
- nginx-build.go
- option.go
- option_test.go
This pull request introduces support for custom SSL libraries in the `nginx-build` tool, enabling users to specify arbitrary SSL implementations like BoringSSL or oqs-provider. It includes updates to workflows, documentation, core logic, and tests to handle these new options seamlessly.
refs: #185 
- **Workflow Updates**:
- Added `run-nginx-boringssl` and `run-nginx-oqs-provider` jobs in `.github/workflows/go.yml` to automate builds with custom SSL libraries like BoringSSL and oqs-provider.
- **Documentation Enhancements**:
- Updated `README.md` to document new options (`-customssl`, `-customsslname`, `-customssltag`) for using custom SSL libraries, including examples for Git repositories and tarball URLs.
- **Core Logic**:
- Updated `builder/builder.go` to add fields `CustomURL`, …
> add support for custom SSL library

- util/file.go
This pull request updates the `ListDirectory` function in `util/file.go` to improve how directory traversal errors are handled and to use more modern Go APIs. The function now uses `filepath.WalkDir`, collects non-fatal errors, and skips directories where permission is denied.
**Improvements to directory listing and error handling:**
* Refactored `ListDirectory` to use `filepath.WalkDir` and `fs.DirEntry` for more efficient directory traversal, and to better handle errors by collecting non-fatal errors and skipping directories with permission errors. The function now returns all files and any accumulated errors encountered during traversal.
**Dependency updates:**
* Added imports for `errors` and `io/fs` to support enhanced error handling and the use of `WalkDir`.
> refactor ListDirectory to use WalkDir with improved error handling

- builder/builder.go
- configure/generate.go
- configure/normalize.go
- download.go
- module3rd/download.go
- module3rd/load.go
- module3rd/load_test.go
- module3rd/module3rd.go
- module3rd/provide.go
- util/file.go
This pull request focuses on improving code consistency, error handling, and naming conventions throughout the codebase. The main changes include standardizing the naming of struct fields and variables (notably changing `Url` to `URL`), simplifying code for better readability, and updating error messages to use Go's `%w` wrapping for better error propagation.
**Naming consistency and code readability:**
- Renamed the `Url` field to `URL` in the `Module3rd` struct and updated all references accordingly across multiple files for consistency with Go naming conventions. [[1]](diffhunk://#diff-6a154e3f27457d5afd9239d0e0438757b250703cdc6c68584054d66f01add7a0L6-R6) [[2]](diffhunk://#diff-24ebc9889619a0cfb3be269b822b456eba9334769c7e46ab9b45da3d9900d61fL32-R39) …
> use staticcheck
