cubicdaiya/nginx-build

configuregen.go, configuregen_test.go, configureopt.go, nginx-build.go, util.go, version.go
Now this implementation has the limitations below.
* `--with-pcre`(force PCRE library usage) is not allowed
* `--with-libatomic`(force libatomic_ops library usage) is not allowed
```
$ nginx-build \
-d work \
-pcre \
--with-debug \
--with-threads \
--prefix=/usr/local/nginx \
--with-mail \
--with-stream
nginx-build: 0.3.5
Compiler: gc go1.4.2
2015/06/08 03:06:19 Download nginx-1.9.1.....
2015/06/08 03:06:19 Download pcre-8.37.....
2015/06/08 03:06:22 Extract nginx-1.9.1.tar.gz.....
2015/06/08 03:06:33 Extract pcre-8.37.tar.gz.....
2015/06/08 03:06:33 Generate configure script for nginx-1.9.1.....
2015/06/08 03:06:33 Configure nginx-1.9.1.....
2015/06/08 03:06:37 Build nginx-1.9.1.....
2015/06/08 03:06:53 Complete building nginx!
nginx version: nginx/1.9.1
built by gcc 4.8.2 (Ubuntu …
```
=> Included nginx configure options to nginx-build.

README.md, nginx-build.go, option.go, patch.go
```
nginx-build \
-d work \
-patch nginx__http2_spdy.patch \
-patch-opt "-p1" \
-v 1.9.7 \
--with-http_spdy_module \
--with-http_v2_module
```
=> introduced new flags: `--patch` and `--patch-opt` for applying patch to nginx

builder/builder.go, builder/builder_test.go, builder/nginx.go, nginx-build.go, option.go
Previously, nginx-build's behavior is not idempotent. So nginx-build always builds nginx.
If **--idempotent** is given, nginx-build does not build nginx when the version of nginx and dependencies (pcre, openssl, zlib) are same. On the other hand, this feature does not affect 3rd party modules.
=> option: introduced --idempotent.

README.md, builder/const.go
http://zlib.net/zlib-1.2.8.tar.gz was not found on its server.
=> Release zlib v1.2.9

builder/const.go
There is not old zlib versions under directly zlib.net. Instead all are archived in fossils.
=> zlib: changed download URL prefix.

builder/const.go
nginx-build has not checked the hash value of the source codes.
If you can use HTTPS, you should download it with HTTPS.
=> change the URLs accessible by HTTPS to HTTPS

README.md, builder/builder.go, builder/builder_test.go, builder/const.go, builder/nginx.go, configure/generate.go, nginx-build.go, option.go
Only libressl does not match option name and software name.
=> Support for LibreSSL

README.md, download.go
refs #1 
This commit works correctly. But an error is displayed when downloading LibreSSL.
```
Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nDate: Sun, 16 Jul 2017 15:04:06 GMT\r\nServer: OpenBSD httpd\r\nConnection: close\r\nCo
ntent-Type: text/html\r\nContent-Length: 439\r\n\r\n<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<title>408 Request Timeout</title>\n<style typ
e=\"text/css\"></style>\n<
/head>\n<body>\n<h1>408 Request Timeout</h1>\n<hr>\n<address>OpenBSD httpd</address>\n</body>\n</html>\n"; err=<nil>
```
cf: https://github.com/golang/go/issues/12855
cf: https://github.com/golang/go/issues/19895
cf: https://github.com/golang/go/issues/2057
Even if an error is …
=> replace wget with the implementation of go

builder/const.go
LibreSSL 2.6.3 is the new stable version.
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.3-relnotes.txt
=> update LibreSSL version to 2.6.3 by default

builder/const.go
LibreSSL 2.6.4 is the new stable version.
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.4-relnotes.txt
=> update LibreSSL version to 2.6.4 by default

builder/const.go
LibreSSL 2.7.2 is the new stable version.
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.7.2-relnotes.txt
=> update LibreSSL version to 2.7.2 by default

download.go
The downloading of the file may be interrupted for some reason.
If it resumes with that, it is judged that the file has been downloaded.
I use broken files.
Save it as a temporary file during downloading and rename it when downloading is completed.
=> save it as a temporary file during downloading

openresty/openresty.go, openresty/openresty_test.go
Currently, as RC versions include an `rcX` suffix, the Name function in
the openresty module won't return a valid result - as one of the version
components will be non-numeric, the `Atoi` call will return an error and
the `ngx_openresty` (used for older versions) will be returned.
=> openresty: support release candidates

util/file.go, util/patch.go
Opening for discussion/consideration:
Make `--patch` flag support directories in addition to regular files; if a
path is detected as a directory, all of its files are resolved, assumed
to be patches, and applied.
I've been using it on my local; if it could potentially benefit others, I'd be
happy to improve the implementation. As it is now, it's not very elegant,
but keeps changes to a minimum.
Possible improvements:
- Make sure expanded files in directories are actually patch files before
applying them - perhaps not needed, as `patch(1)` itself will validate
- We could try to avoid creating a new array, and expand in the same 
`pathes` array
- ~As of now, all files in directories are assumed to be patches, so no
support for nested directories~ (this is now implemented)
=> support patches directory

builder/const.go
this version fails to build on mac.
But I can build it on Linux. It is not a problem with nginx-build.
=> bumped default LibreSSL version to 2.9.2

builder/const.go
OpenSSL 1.0.2 will be End Of Life at the end of this year.
So, we should use OpenSSL 1.1.1 as the default version.
cf: https://www.openssl.org/blog/blog/2019/11/07/3.0-update/
=> use OpenSSL 1.1.1 as the default version

builder/const.go
refs:
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.0.2-relnotes.txt
=> bumped default LibreSSL version to 3.0.2

.github/workflows/go.yml
=> ci: use go1.16 in GitHub Actions.

Makefile
Go1.16 started to support a build with GOOS=darwin,GOARCH=arm64.
https://golang.org/doc/go1.16
=> build: darwin-arm64 binary.

builder/const.go
The latest stable release is 3.2.4
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.4-relnotes.txt
=> update LibreSSL version to 3.2.4

builder/const.go
The latest stable release is 3.3.4
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.3.4-relnotes.txt
=> update LibreSSL version to 3.3.4

builder/builder.go
OpenSSL 3.0.0 is released. If you provide -idempotent option, it fails now.
close: #53
=> support new OpenSSL version scheme

builder/const.go
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.2-relnotes.txt
=> bumped default libressl version to 3.5.2

.github/workflows/release.yml, .goreleaser.yml
refs: #78
I recommend using `debug.ReadBuildInfo` to manage the version automatically.
If you only use binary releases, you can use this change. But It's hard check for me.
=> use goreleaser for auto binary release

nginx-build.go, util/file.go
These are deprecated from Go1.16.
=> style: migrate functions in io/ioutils package to os package.

module3rd/load.go
When failing to unmarshal JSON that modulesConfPath, nginx-build shows error like:
```
invalid character 'g' in literal null (expecting 'u')
```
This message doesn't tell enough information to fix. This p-r makes showing more contextual informations.
=> Add more context when failing to unmarshal JSON

version.go
Previously, `nginx-build -versions` intended to output all nginx versions contain old versions. Since this behavior is noisy and not very helpful, this PR changes this behavior to output only the latest stable version.
=> simplified the output of "nginx-build -versions".

.github/workflows/go.yml
- use v3 for checkout and setup-go instead of v2
- update go version from 1.17 to 1.18.x
- removed unnecessary installation process in Run
=> ci: update actions and refactored.

builder/const.go
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.1-relnotes.txt
=> bumped default libressl version to 3.6.1

builder/const.go
I used this, but version 1.2.13 of zlib was not available.
cf: https://madler.net/pipermail/zlib-announce_madler.net/2023/000014.html
=> bumped default zlib version to 1.3

builder/const.go, renovate.json
This commit introduces automated updates using Renovate. It includes the handling of updates not only for LibreSSL, zlib, and pcre, but also for other libraries and GitHub Actions as needed. This aims to keep our project up-to-date with the latest security patches and features.
=> automated updates using Renovate

builder/const.go, renovate.json
We changed how we look at LibreSSL releases. Now, if the patch number is 0, we don't use it. These are testing releases. This helps us only focus on stable or important releases.
=> [renovate] Skip LibreSSL releases with patch 0

renovate.json
This pull request includes a modification to the `renovate.json` file. The change updates the `extractVersionTemplate` regex to only match even minor version numbers in the release tag.
=> Update version of freenginx extraction regex pattern in renovate config

.github/workflows/go.yml, .github/workflows/release.yml
This pull request includes updates to the Go version used in the GitHub Actions workflows. The changes are made in two different workflow files: `go.yml` and `release.yml`. Both files have been updated to use Go version `1.22.x` instead of `1.21.x`.
Updates to Go version:
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL13-R13): Updated the Go version used in the `Set up Go` action from `1.21.x` to `1.22.x`.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L15-R15): Updated the Go version used in the `Setup Go` action from `1.21.x` to `1.22.x`.
=> Update Go version to 1.22.x in workflows

.github/workflows/release.yml
This pull request includes a change to the `.github/workflows/release.yml` file. The `args` option in the `goreleaser/goreleaser-action` has been updated from `release --rm-dist` to `release --clean`. This change modifies the command-line arguments passed to the GoReleaser action in the GitHub workflow, replacing the `--rm-dist` flag with the `--clean` flag.
=> Update goreleaser action to use --clean instead of --rm-dist

renovate.json
This pull request includes a change to the `renovate.json` file to add a new regex manager for managing the Go version in GitHub workflows.
Configuration updates:
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57R7-R16): Added a new regex manager to manage the Go version in `.github/workflows/release.yml` using the `golang-version` datasource.
=> Add golang-version regex manager for GitHub workflows in renovate.json

.github/workflows/go.yml
This pull request includes an update to the Go version in the GitHub Actions workflow file to ensure compatibility with the latest Go features and improvements.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL13-R13): Updated Go version from `1.22.x` to `1.23.x` to utilize the latest features and improvements in Go.
=> Update Go version from 1.22.x to 1.23.x in GitHub Actions workflow

builder/builder.go, builder/builder_test.go, builder/const.go
This pull request includes changes to the `builder` package to update the URL structure for downloading OpenSSL. The most important changes include modifying the URL format in the `MakeBuilder` function, updating the corresponding test cases, and changing the OpenSSL download URL prefix.
* [`builder/builder.go`](diffhunk://#diff-d371e466d16c4d92dff29b2806e847c619149cd6de147f1cb9ae7e9511d5da7fL161-R161): Modified the `MakeBuilder` function to include the OpenSSL version in the `DownloadURLPrefix` format. (`[builder/builder.goL161-R161](diffhunk://#diff-d371e466d16c4d92dff29b2806e847c619149cd6de147f1cb9ae7e9511d5da7fL161-R161)`)
* [`builder/builder_test.go`](diffhunk://#diff-0b6515a22d5e5673e7fad3d1f3576a7b89aa6ee7f38aa7c583c12f4a63a0a4feL113-R113): Updated the `TestDownloadURL` test case …
=> Update OpenSSL download URL to GitHub releases

LICENSE, message.go
This pull request includes updates to the copyright year in the `LICENSE` and `message.go` files.
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L1-R1): Updated the copyright year to remove the end year.
* [`message.go`](diffhunk://#diff-2ce052ca28a77c3b54be26bfc568dddef91bf239253d0ad537609af1731032d4L31-R31): Updated the copyright year in the `printNginxBuildVersion` function.
=> Update copyright year in LICENSE and message.go from 2022 to 2014

.github/workflows/go.yml, builder/const.go
This pull request includes updates to the `go.yml` workflow and the `const.go` file to support a new version of OpenResty and add a new build configuration.
Workflow updates:
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR27): Added a new build configuration for OpenResty. (`[.github/workflows/go.ymlR27](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR27)`)
Version updates:
* [`builder/const.go`](diffhunk://#diff-df8a40b36330190dbbca89642040400981eaea7d0a3e94ce641f882854b2d8b5L35-R35): Updated the OpenResty version from `1.25.3.2` to `1.27.1.1`. (`[builder/const.goL35-R35](diffhunk://#diff-df8a40b36330190dbbca89642040400981eaea7d0a3e94ce641f882854b2d8b5L35-R35)`)
=> Update OpenResty version to 1.27.1.1 and add CI

renovate.json
This pull request includes a small change to the `renovate.json` file. The change modifies the `extractVersionTemplate` to correctly match versions with any number of digits in the patch version.
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L85-R85): Updated `extractVersionTemplate` to match versions with any number of digits in the patch version.
=> Update version extraction regex for LibreSSL

.github/workflows/go.yml
This pull request updates the GitHub Actions workflow for the Go project to include additional jobs for running Nginx with different SSL libraries. The most important changes include the addition of new jobs for running Nginx with OpenSSL, LibreSSL, FreeNginx, and OpenResty.
Enhancements to GitHub Actions workflow:
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR4-R68): Added a new job `run-nginx-openssl` to run Nginx with OpenSSL.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR4-R68): Added a new job `run-nginx-libressl` to run Nginx with LibreSSL.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR …
=> Add multiple Nginx build jobs

download.go
This pull request includes a change to the `download.go` file to improve error handling during the download process.
Error handling improvement:
* [`download.go`](diffhunk://#diff-185eea976fbefe704cffdd8264c8acb8748cf6a078a08b9b8790623721422352R32-R35): Added a check for the HTTP status code to ensure it is `http.StatusOK` before proceeding with the download. If the status code is not `http.StatusOK`, the function returns an error with a descriptive message.
=> Add error handling for non-200 status codes in download function.

builder/builder.go
This refactoring separates the concepts of DownloadURL and ArchivePath, which were previously combined in the code. These are fundamentally different concepts and should not be handled together.
Changes include:
- Adding a `DownloadURL()` method to handle download links independently.
- Updating `Name()` to only return the logical name of the component.
This improves code clarity, flexibility, and maintainability for future extensions.
=> Refactor: Separate DownloadURL and ArchivePath in Builder

renovate.json
This pull request includes a small change to the `renovate.json` file. The change updates the `extractVersionTemplate` to ensure that only numerical versions are matched.
=> update extractVersionTemplate regex to match version format correctly

README.md
Following PR #85, the `--add-module` and `--add-dynamic-module` options are no longer available.
=> docs: remove --add-module and --add-dynamic-module

.github/workflows/renovate-config-validator-ci.yml
This pull request updates the Renovate configuration validation workflow to ensure the latest version of the Renovate package is used during validation.
* [`.github/workflows/renovate-config-validator-ci.yml`](diffhunk://#diff-e519a4bcca8b109726730f425f70681c1ebc03420db40b019c222ff042b1fd76L20-R20): Updated the `run` command to use `renovate@latest` when validating `renovate.json`, ensuring the workflow always uses the latest version of the Renovate package.
=> update renovate validation step to use latest renovate package version

module3rd/load.go
This pull request includes a small but important change to the `Load` function in `module3rd/load.go`. The change ensures that the file handle (`f`) is properly closed after use by adding a `defer f.Close()` statement.
=> fix: close file after loading module configuration

nginx-build.go
This pull request includes minor changes to improve error message clarity in the `nginx-build.go` file. The changes simplify the wording of log messages when a working directory cannot be created.
Error message improvements:
* [`nginx-build.go`](diffhunk://#diff-667ffbacfd12ee2bb5af7dbbab9564ac510094328149f2d02b25bca5b94c6492L247-R247): Updated log messages in `func main()` to remove redundant phrasing and improve readability when reporting failure to create a working directory. [[1]](diffhunk://#diff-667ffbacfd12ee2bb5af7dbbab9564ac510094328149f2d02b25bca5b94c6492L247-R247) [[2]](diffhunk://#diff-667ffbacfd12ee2bb5af7dbbab9564ac510094328149f2d02b25bca5b94c6492L270-R270)
=> Simplify directory creation errors

.github/workflows/codeql.yml
This pull request updates the CodeQL workflow configuration to expand the set of languages analyzed during code scanning. Specifically, it adds support for analyzing GitHub Actions workflows in addition to Go code.
Enhancement to CodeQL analysis:
* [`.github/workflows/codeql.yml`](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27L43-R43): Updated the `language` matrix in the CodeQL job to include `"actions"` alongside `"go"`, enabling security and quality analysis for GitHub Actions workflows as well as Go code.
=> Add actions language to CodeQL analysis matrix in workflow YAML

.github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/renovate-config-validator-ci.yml, .github/workflows/security.yml
This pull request updates several GitHub Actions workflow files to explicitly set the required permissions for each workflow. This helps improve security by ensuring each workflow only has the minimum permissions necessary for its tasks.
**Workflow permission updates:**
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR6-R8): Sets `contents: read` permission to restrict the workflow to read-only access to repository contents.
* [`.github/workflows/renovate-config-validator-ci.yml`](diffhunk://#diff-e519a4bcca8b109726730f425f70681c1ebc03420db40b019c222ff042b1fd76R10-R12): Sets `contents: read` permission for the Renovate config validator workflow.
* [`.github/workflows/security.yml`](diffhunk://#diff-6102d4f2cddb56c446459bde9bf8 …
=> Add explicit permissions for contents in GitHub workflow files

config/configure.example, configure/configure_test.go, configure/normalize.go, nginx-build.go
This pull request enhances how trailing comments are handled in generated configure scripts, ensuring that any comments at the end of the input are preserved in the output. The main changes involve updating the normalization logic, the main build process, and adding a new test to verify this behavior.
**Improvements to configure script normalization and generation:**
* The `Normalize` function in `configure/normalize.go` now returns both the base configure script and any trailing comment lines, preserving comments that start with `#` at the end of the input.
* The main build logic in `nginx-build.go` is updated to append any captured trailing comments to the generated configure script, ensuring they are retained in the output file. …
=> Preserve trailing comments in configure script generation and loading

.github/workflows/codeql.yml, .github/workflows/go.yml, .github/workflows/security.yml
This pull request updates the workflow triggers for several GitHub Actions to make them more efficient by restricting when they run. The workflows will now only execute when relevant files or directories are changed, reducing unnecessary runs and improving CI performance.
**Workflow trigger improvements:**
* [`.github/workflows/codeql.yml`](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R17-R44): Added `paths` filters to both `push` and `pull_request` events so the CodeQL workflow only runs when Go source files, related configuration files, or workflow files are modified.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR5-R19): Added `paths` filters to the `pull_request` event to ensure the …
=> Add path filters to workflows for targeted CI runs
